#!/bin/sh
# This script is generated by Matugen to set the TTY colors for Ly
# It is called by ly.service via ExecStartPre

# Redefine TTY colors using escape codes
# \033]P0RRGGBB sets color index 0 (background)
# \033]P7RRGGBB sets color index 7 (foreground)
# \033c triggers a terminal reset to apply the changes

printf "\033]P0{{colors.surface.default.hex_stripped}}\033]P7ffffff\033c" > /dev/tty2
