# Ly supports 24-bit true color with styling, which means each color is a 32-bit value.
# The format is 0xSSRRGGBB, where SS is the styling, RR is red, GG is green, and BB is blue.

# Allow empty password or not when authenticating
allow_empty_password = true

# The active animation
# none, doom, matrix, colormix, gameoflife, dur_file
animation = none

# Stop the animation after some time (0 = forever)
animation_timeout_sec = 0

# The character used to mask the password
asterisk = *

# Failed authentications before special animation
auth_fails = 10

# Battery ID (null to disable)
battery_id = null

# PAM service name for autologin
auto_login_service = ly-autologin
auto_login_session = null
auto_login_user = null

# Colors (Managed by Matugen + TTY Palette)
# bg = 0 uses the TTY color 0, which we redefine in ExecStartPre
bg = 0
fg = 7
border_fg = 0x00FFFFFF
error_bg = 0
error_fg = 0x01FF0000
cmatrix_fg = 0x0000FF00
gameoflife_fg = 0x0000FF00

# Render true colors (Disabled to use the TTY palette instead)
full_color = false

# Clock (null to disable)
clock = null

# Input box active by default on startup
default_input = login

# Input boxes length
input_len = 34

# Active language
lang = en

# Log files
ly_log = /var/log/ly.log
session_log = .local/state/ly-session.log

# Main box margins
margin_box_h = 2
margin_box_v = 1

# Path
path = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Keybindings
restart_key = F2
restart_cmd = /sbin/shutdown -r now
shutdown_key = F1
shutdown_cmd = /sbin/shutdown -h now
sleep_key = F3

# Save the current desktop and login as defaults
save = true

# Service name
service_name = ly

# Setup command
setup_cmd = /etc/ly/setup.sh

# Center the session name
text_in_center = false

# Xorg settings
x_cmd = /usr/bin/X
xauth_cmd = /usr/bin/xauth
xinitrc = ~/.xinitrc
waylandsessions = /usr/share/wayland-sessions
xsessions = /usr/share/xsessions
